local_backend: true

backend:
  name: git-gateway
  branch: master

media_folder: public/img
public_folder: /img

collections:
  - name: "cv"
    label: "Življenjepis"
    format: "json"
    files:
      - name: "workExperiences"
        label: "Delovne izkušnje"
        format: "json"
        file: "content/cv/work-experiences.json"
        create: true
        slug: "{{slug}}"
        fields:
          - label: "Entiteta"
            name: "entries"
            widget: "list"
            fields:
              - { label: 'Podjetje', name: 'entityName', widget: 'string', required: true }
              - { label: 'Pozicija', name: 'position', widget: 'string', required: true }
              - { label: 'Leta', name: 'years', widget: 'string', required: true }
              - { label: 'Opis', name: 'description', widget: 'list', field: {label: 'Paragraph', name: 'Paragraph', widget: 'text'} }

      - name: "education"
        label: "Izobrazba"
        format: "json"
        file: "content/cv/education.json"
        create: true
        slug: "{{slug}}"
        fields:
          - label: "Entiteta"
            name: "entries"
            widget: "list"
            fields:
              - { label: 'Ustanova', name: 'entityName', widget: 'string', required: true }
              - { label: 'Pozicija', name: 'position', widget: 'string', required: true }
              - { label: 'Leta', name: 'years', widget: 'string', required: true }
              - { label: 'Opis', name: 'description', widget: 'list', field: { label: 'Paragraph', name: 'Paragraph', widget: 'text' } }

      - name: "otherHighlights"
        label: "Ostali poudarki"
        format: "json"
        file: "content/cv/other-highlights.json"
        create: true
        slug: "{{slug}}"
        fields:
          - label: "Entiteta"
            name: "entries"
            widget: "list"
            fields:
              - { label: 'Poudarek', name: 'entityName', widget: 'string', required: true }
              - { label: 'Naslov', name: 'position', widget: 'string', required: true }
              - { label: 'Leta', name: 'years', widget: 'string', required: true }
              - { label: 'Opis', name: 'description', widget: 'list', field: { label: 'Paragraph', name: 'Paragraph', widget: 'text' } }