local_backend: true

backend:
  name: git-gateway
  branch: master

media_folder: public/img
public_folder: /img

collections:
  - name: "cv"
    label: "Življenjepis"
    fields:
      - name: 'workExperiences'
        label: 'Delovne izkušnje'
        widget: 'list'
        fields:
          - { label: 'Podjetje', name: 'company', widget: 'string', required: true }
          - { label: 'Pozicija', name: 'position', widget: 'string', required: true }
          - { label: 'Leta', name: 'years', widget: 'string', required: true }
          - { label: 'Opis', name: 'description', widget: 'list', field: {label: 'Opis', name: 'description', widget: string} }
